### ISSUE TITLE
Made dataset splits possible during export

### ISSUE THREAD

**Issue by Arthemide** [kili-technology/kili-python-sdk#1162]
I am working on a project using Kili and exporting my datasets with different types of annotations.

I think it would be useful to add a new feature that allows me to split the datasets into train/validation/test sets directly during the export process.
Currently, I have to create another script after the Kili export, and I believe that every other data scientist has to do the same.

Is this feature being developed internally, and do you think it would be a valuable addition?

**Comment by Jonas1312** [comment]
Hi,

If you want to create three separate exports for your three folds, you can try to use the `asset_ids`, `external_ids` or `asset_filter_kwargs` parameters of the [`kili.export_labels()`](https://python-sdk-docs.kili-technology.com/latest/sdk/label/#kili.entrypoints.queries.label.__init__.QueriesLabel.export_labels) method.

For example, you can get the asset ids using `kili.assets()`, then split those ids into three folds, and call the `kili.export_labels()` method thrice using the `asset_ids` parameter and the different folds.

Would this solution solve your issue?
