### ISSUE TITLE
Correction du lien vers le notebook "Basic Project Setup"

### ISSUE THREAD

**Issue by phileas-condemine** [kili-technology/kili-python-sdk#907]
Dans la doc située ici : https://python-sdk-docs.kili-technology.com/2.127/sdk/tutorials/basic_project_setup/
le lien renvoie un code 404 https://python-sdk-docs.kili-technology.com/2.127/sdk/tutorials/basic_project_setup/

**Comment by Jonas1312** [comment]
Bonjour,

Merci pour le signalement. La doc sera mise à jour demain avec quelques changements.

D'ici là, le tutoriel pour le basic project setup est disponible ici : https://github.com/kili-technology/kili-python-sdk/blob/master/recipes/tutorials/basic_project_setup.ipynb

**Comment by phileas-condemine** [comment]
OK merci 🤗
