### ISSUE TITLE
Comment mettre à jour l'interface (ontologie) grâce au SDK ?

### ISSUE THREAD

**Issue by phileas-condemine** [kili-technology/kili-python-sdk#908]
Je crée un JSON en suivant les recommandations de la doc :
https://docs.kili-technology.com/docs/customizing-project-interface 
https://docs.kili-technology.com/docs/customizing-the-interface-through-json-settings
Mais cette documentations fait uniquement référence au studio.
Comment publier le JSON grâce au SDK ?

**Comment by phileas-condemine** [comment]
J'ai l'impression qu'on peut le faire avec la méthode update_properties_in_project : https://python-sdk-docs.kili-technology.com/2.127/sdk/project/#kili.mutations.project.__init__.MutationsProject.update_properties_in_project
Je vais tester.
Ca serait intéressant de l'ajouter à la documentation : https://docs.kili-technology.com/docs/customizing-the-interface-through-json-settings

**Comment by Jonas1312** [comment]
Bonjour,

Pour mettre à jour la json interface du projet, il faut utiliser la fonction [kili.update_properties_in_project()](https://python-sdk-docs.kili-technology.com/2.127/sdk/project/#kili.mutations.project.__init__.MutationsProject.update_properties_in_project) pour un projet existant, ou [kili.create_project()](https://python-sdk-docs.kili-technology.com/2.127/sdk/project/#kili.mutations.project.__init__.MutationsProject.create_project), en passant un dictionnaire python à l'argument `json_interface`
