### ISSUE TITLE
export_labels() sur Databricks renvoie "No such file or directory"

### ISSUE THREAD

**Issue by phileas-condemine** [kili-technology/kili-python-sdk#930]
J'exécute le code suivant sur Azure Databricks
```
from kili.client import Kili

kili = Kili(api_key=api_key['kili-secret'])

path_to_labels = "/databricks/driver/export.zip"

kili.export_labels(project_id=project_id,filename = path_to_labels,fmt="kili",layout = "merged",single_file=True,asset_ids=list("cld3aqa68078x0jw2ds463b3k"),with_assets=False)

```

renvoie l'erreur suivante : 

> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpx9xpowaa/clbgd78ic00sw0k3a0y0dcbgv/data.json'

Avec le traceback : 

> 
> FileNotFoundError                         Traceback (most recent call last)
> <command-3803611707634296> in <cell line: 2>()
>       1 path_to_labels = "/databricks/driver/export.zip"
> ----> 2 kili.export_labels(project_id=project_id,filename = path_to_labels,fmt="kili",layout = "merged",single_file=True,asset_ids=list("cld3aqa68078x0jw2ds463b3k"),with_assets=False)
> 
> /databricks/python/lib/python3.9/site-packages/kili/queries/label/__init__.py in export_labels(self, project_id, filename, fmt, asset_ids, layout, single_file, disable_tqdm, with_assets, external_ids)
>     310 
>     311         try:
> --> 312             services.export_labels(
>     313                 self,
>     314                 asset_ids=asset_ids,
> 
> /databricks/python/lib/python3.9/site-packages/kili/services/export/__init__.py in export_labels(kili, asset_ids, project_id, export_type, label_format, split_option, single_file, output_file, disable_tqdm, log_level, with_assets)
>      82         )  # ensures full mapping
>      83         exporter_class = format_exporter_selector_mapping[label_format]
> ---> 84         exporter_class(
>      85             export_params, kili, logger, disable_tqdm, content_repository
>      86         ).export_project()
> 
> /databricks/python/lib/python3.9/site-packages/kili/services/export/format/base.py in export_project(self)
>     157                 local_media_dir=str(self.images_folder),
>     158             )
> --> 159             self.process_and_save(assets, self.output_file)
>     160 
>     161     @property
> 
> /databricks/python/lib/python3.9/site-packages/kili/services/export/format/kili/__init__.py in process_and_save(self, assets, output_filename)
>      55         """
>      56         clean_assets = self.process_assets(assets, self.label_format)
> ---> 57         return self._save_assets_export(
>      58             clean_assets,
>      59             output_filename,
> 
> /databricks/python/lib/python3.9/site-packages/kili/services/export/format/kili/__init__.py in _save_assets_export(self, assets, output_filename)
>      34         if self.single_file:
>      35             project_json = json.dumps(assets, sort_keys=True, indent=4)
> ---> 36             with (self.base_folder / "data.json").open("wb") as output_file:
>      37                 output_file.write(project_json.encode("utf-8"))
>      38         else:
> 
> /usr/lib/python3.9/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
>    1240         the built-in open() function does.
>    1241         """
> -> 1242         return io.open(self, mode, buffering, encoding, errors, newline,
>    1243                        opener=self._opener)
>    1244 
> 
> /usr/lib/python3.9/pathlib.py in _opener(self, name, flags, mode)
>    1108     def _opener(self, name, flags, mode=0o666):
>    1109         # A stub for the opener argument to built-in open()
> -> 1110         return self._accessor.open(self, flags, mode)
>    1111 
>    1112     def _raw_open(self, flags, mode=0o777):
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpx9xpowaa/clbgd78ic00sw0k3a0y0dcbgv/data.json'

**Comment by phileas-condemine** [comment]
Désolé je n'ai pas fait attention au problème lors du copier-coller de l'erreur, j'ai modifier mon message précédent avec l'erreur et le traceback

**Comment by Jonas1312** [comment]
Un fix est en cours de review

**Comment by Jonas1312** [comment]
Un patch 2.128.2 a été déployé, et devrait corriger le problème rencontré
