### ISSUE TITLE
Mise à jour de la documentation/reference create_predictions() pour les paramètres model_name_array & model_name

### ISSUE THREAD

**Issue by phileas-condemine** [kili-technology/kili-python-sdk#933]
Lorsqu'on utilise utilise create_predictions() avec le paramètre on obtient un message de warning informant que model_name_array est un paramètre déprécié et qu'il faut utiliser model_name.
Le paramètre model_name ne figure pas dans la doc
Le parmaètre model_name_array n'est pas signalé comme déprécié dans la doc

**Comment by theodu** [comment]
Bonjour, merci pour le retour!
On va corriger ca dans la prochaine version de la doc qu'on releasera! Il faut effectivement utiliser `model_name` comme dit dans le warning
Théo
